[package]
name = "reddit_news_checker"
version = "0.2.1"
authors = ["phil <ph-ketteni@t-online.de>"]
edition = '2018'

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = {version = "0.10.1", features = ["blocking"]}
argparse = "0.2.2"
